export const FETCH_PRODUCTS= "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_TYPE_SIZE="FILTER_PRODUCTS_BY_TYPE_SIZE";
// export const FILTER_PRODUCTS_BY_SIZE="FILTER_PRODUCTS_BY_SIZE";
export const SORT_PRODUCTS="SORT_PRODUCTS";